#!/bin/bash

# Load SMTP properties from the configuration file
SMTP_CONFIG_FILE="smtp_config.properties"
if [ ! -f "$SMTP_CONFIG_FILE" ]; then
  echo "SMTP configuration file not found!"
  exit 1
fi

# Read SMTP configuration from properties file
SMTP_HOST=$(grep -i 'smtp_host' $SMTP_CONFIG_FILE | cut -d '=' -f2)
SMTP_PORT=$(grep -i 'smtp_port' $SMTP_CONFIG_FILE | cut -d '=' -f2)
SMTP_USERNAME=$(grep -i 'smtp_username' $SMTP_CONFIG_FILE | cut -d '=' -f2)
SMTP_PASSWORD=$(grep -i 'smtp_password' $SMTP_CONFIG_FILE | cut -d '=' -f2)
FROM_EMAIL=$(grep -i 'from_email' $SMTP_CONFIG_FILE | cut -d '=' -f2)

# Define the email details from the script arguments
ALERT_CODE=$1
MESSAGE=$2
TO_EMAIL=$3
CC_EMAIL=$4
BUSINESS=$5

# Validate input parameters
if [ -z "$TO_EMAIL" ]; then
  echo "Error: No recipient email provided."
  exit 1
fi

FOOTER_PATTERN="\\*+ IMPORTANT MESSAGE"
CLEANED_MESSAGE=$(echo "$MESSAGE" | sed "/$FOOTER_PATTERN/,\$d")

# Prepare email subject and body
SUBJECT="Alert: $ALERT_CODE - $BUSINESS"
BODY="Alert Code: $ALERT_CODE\nMessage: $CLEANED_MESSAGE\nBusiness: $BUSINESS\n\nThanks and Regards,\nCDAO Team"


# Send the email using msmtp
send_email() {
  # Use msmtp to send the email via the configured SMTP server
  (
    echo "From: $FROM_EMAIL"
    echo "To: $TO_EMAIL"
    if [ -n "$CC_EMAIL" ]; then
      echo "Cc: $CC_EMAIL"
    fi
    echo "Subject: $SUBJECT"
    echo ""
    echo -e "$BODY"
  ) | msmtp --host=$SMTP_HOST --port=$SMTP_PORT --auth=on --user=$SMTP_USERNAME --passwordeval="echo $SMTP_PASSWORD" --from=$FROM_EMAIL $TO_EMAIL
  
  # Check if msmtp ran successfully
  if [ $? -eq 0 ]; then
    echo "Email sent to $TO_EMAIL and CC: $CC_EMAIL"
  else
    echo "Failed to send email"
  fi
}

# Call the send_email function
send_email
