#!/bin/bash

# Define the path to your Spark job's JAR file and main class
SPARK_JAR_PATH="/path/to/your/jar/email-notification-app_2.12-0.1.jar"
SPARK_MAIN_CLASS="EmailNotificationApp"
SPARK_MASTER="spark://your-spark-master:7077"  # Adjust if you're using a different master

# Submit the Spark job using spark-submit
spark-submit --class $SPARK_MAIN_CLASS --master $SPARK_MASTER $SPARK_JAR_PATH
